### ISSUE TITLE
[simgear] 2020.3.17-1 build error

### ISSUE THREAD

**Issue by josh027020** [acxz/flightgear-arch#7]
make[2]: *** [simgear/CMakeFiles/SimGearScene.dir/build.make:1826: simgear/CMakeFiles/SimGearScene.dir/scene/viewer/Compositor.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:887: simgear/CMakeFiles/SimGearScene.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

**Comment by geeregman** [comment]
I get same error, can't figure it out .....

make[2]: *** [simgear/CMakeFiles/SimGearScene.dir/build.make:1854: simgear/CMakeFiles/SimGearScene.dir/scene/viewer/CompositorPass.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:887: simgear/CMakeFiles/SimGearScene.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: simgear

**Comment by lemust83** [comment]
Hi! Sorry for my poor English.
I'm a Manjaro user and Archlinux user for long time. Flightgear with dependencies such simgear is installed for long time too. But since the last version 2020.3.17, there is a cmake error at step 95% :
Log bellow with some french words but no necessary to translate.

[ 95%] Building CXX object simgear/CMakeFiles/SimGearScene.dir/scene/viewer/ClusteredShading.cxx.o
/tmp/simgear/src/simgear-2020.3.17/simgear/scene/util/SGProgram.cxx: Dans la fonction membre « virtual void SGProgram::apply(osg::State&) const »:
/tmp/simgear/src/simgear-2020.3.17/simgear/scene/util/SGProgram.cxx:58:31: attention: comparaison d'expressions entières de types signés différents: « int » et « unsigned int » [-Wsign-compare]
   58 |             for (int i = 0; i < getNumShaders(); ++i) {
      |                             ~~^~~~~~~~~~~~~~~~~
/tmp/simgear/src/simgear-2020.3.17/simgear/scene/util/SGProgram.cxx:69:27: attention: comparaison d'expressions entières de types signés différents: « int » et « unsigned int » [-Wsign-compare]
   69 |         for (int i = 0; i < getNumShaders(); ++i) {
      |                         ~~^~~~~~~~~~~~~~~~~
[ 95%] Building CXX object simgear/CMakeFiles/SimGearScene.dir/scene/viewer/Compositor.cxx.o
Dans le fichier inclus depuis /tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.cxx:17:
/tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.hxx:137:34: erreur: le champ « _uniforms » a le type incomplet « simgear::compositor::Compositor::BuiltinUniforms » {aka « std::array<osg::ref_ptr<osg::Uniform>, 14> »}
  137 |     BuiltinUniforms              _uniforms;
      |                                  ^~~~~~~~~
Dans le fichier inclus depuis /usr/include/c++/12.2.1/bits/hashtable_policy.h:34,
                 depuis /usr/include/c++/12.2.1/bits/hashtable.h:35,
                 depuis /usr/include/c++/12.2.1/unordered_map:46,
                 depuis /tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.hxx:20:
/usr/include/c++/12.2.1/tuple:1595:45: note: déclaration de « simgear::compositor::Compositor::BuiltinUniforms » {aka « struct std::array<osg::ref_ptr<osg::Uniform>, 14> »}
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
[ 95%] Building CXX object simgear/CMakeFiles/SimGearScene.dir/scene/viewer/CompositorBuffer.cxx.o
Dans le fichier inclus depuis /tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/CompositorBuffer.cxx:33:
/tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/Compositor.hxx:137:34: erreur: le champ « _uniforms » a le type incomplet « simgear::compositor::Compositor::BuiltinUniforms » {aka « std::array<osg::ref_ptr<osg::Uniform>, 14> »}
  137 |     BuiltinUniforms              _uniforms;
      |                                  ^~~~~~~~~
Dans le fichier inclus depuis /usr/include/c++/12.2.1/bits/stl_map.h:63,
                 depuis /usr/include/c++/12.2.1/map:61,
                 depuis /usr/include/osg/GLExtensions:24,
                 depuis /usr/include/osg/BufferObject:19,
                 depuis /usr/include/osg/Image:17,
                 depuis /usr/include/osg/Texture:18,
                 depuis /tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/CompositorBuffer.hxx:20,
                 depuis /tmp/simgear/src/simgear-2020.3.17/simgear/scene/viewer/CompositorBuffer.cxx:17:
/usr/include/c++/12.2.1/tuple:1595:45: note: déclaration de « simgear::compositor::Compositor::BuiltinUniforms » {aka « struct std::array<osg::ref_ptr<osg::Uniform>, 14> »}
 1595 |   template<typename _Tp, size_t _Nm> struct array;
      |                                             ^~~~~
make[2]: *** [simgear/CMakeFiles/SimGearScene.dir/build.make:1826: simgear/CMakeFiles/SimGearScene.dir/scene/viewer/Compositor.cxx.o] Error 1
make[2]: *** Attente des tâches non terminées....
make[2]: *** [simgear/CMakeFiles/SimGearScene.dir/build.make:1840: simgear/CMakeFiles/SimGearScene.dir/scene/viewer/CompositorBuffer.cxx.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:887: simgear/CMakeFiles/SimGearScene.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
==> ERREUR : Une erreur s’est produite dans build().

Abandon…

I did downgrade cmake and typed makepkg -si with same error.

Thanks
